// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Sheeter
{
    using Key_ = int;
    using Data_ = ExampleData;
    using Store_ = Dictionary<int, ExampleData>;

    /// <summary>
    /// example.xlsx#Data
    /// </summary>
    public partial class ExampleData
    {
        /// <summary>
        /// note1
        /// </summary>
        [JsonProperty("Name1")]
        public int Name1 { get; set; }

        /// <summary>
        /// note2
        /// </summary>
        [JsonProperty("Name2")]
        public int Name2 { get; set; }

        /// <summary>
        /// note3
        /// </summary>
        [JsonProperty("Name3")]
        public int Name3 { get; set; }

        /// <summary>
        /// note4
        /// </summary>
        [JsonProperty("Name4")]
        public int Name4 { get; set; }

        /// <summary>
        /// note5
        /// </summary>
        [JsonProperty("Name5")]
        public int Name5 { get; set; }
    }

    /// <summary>
    /// example.xlsx#Data
    /// </summary>
    public partial class ExampleDataReader : Reader
    {
        /// <summary>
        /// 取得檔名物件
        /// </summary>
        public FileName FileName()
        {
            return new FileName("exampleData", ".json");
        }

        /// <summary>
        /// 讀取資料
        /// </summary>
        public string FromData(string data, bool clear, Progress progress)
        {
            Store_ tmpl;

            try
            {
                tmpl = JsonConvert.DeserializeObject<Store_>(data);
            } // try
            catch
            {
                return "from data: deserialize failed";
            } // catch

            if (tmpl == null)
                return "from data: deserialize failed";

            if (clear)
                this.data = new();

            var task = progress.Reg();
            var curr = 0;
            var total = tmpl.Count;

            foreach (var itor in tmpl)
            {
                if (this.data.ContainsKey(itor.Key))
                    return "from data: key duplicate [exampleData : " + itor.Key + "]";

                this.data[itor.Key] = itor.Value;
                curr++;
                progress.Set(task, curr, total);
            } // for

            return string.Empty;
        }

        /// <summary>
        /// 清除資料
        /// </summary>
        public void Clear()
        {
            data.Clear();
        }

        /// <summary>
        /// 取得資料
        /// </summary>
        public bool TryGetValue(Key_ key, out Data_ value)
        {
            return data.TryGetValue(key, out value);
        }

        /// <summary>
        /// 檢查索引是否存在
        /// </summary>
        public bool ContainsKey(Key_ key)
        {
            return data.ContainsKey(key);
        }

        /// <summary>
        /// 取得迭代器
        /// </summary>
        public IEnumerator<KeyValuePair<Key_, Data_>> GetEnumerator()
        {
            return data.GetEnumerator();
        }

        /// <summary>
        /// 取得資料
        /// </summary>
        public Data_ this[Key_ key]
        {
            get { return data[key]; }
        }

        /// <summary>
        /// 取得索引列表
        /// </summary>
        public ICollection<Key_> Keys
        {
            get { return data.Keys; }
        }

        /// <summary>
        /// 取得資料列表
        /// </summary>
        public ICollection<Data_> Values
        {
            get { return data.Values; }
        }

        /// <summary>
        /// 取得資料數量
        /// </summary>
        public int Count
        {
            get { return data.Count; }
        }

        private Store_ data = new Store_();
    }
}
