package builds

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"

	"github.com/yinweli/Sheeter/testdata"
)

func TestBuildJsonGo(t *testing.T) {
	suite.Run(t, new(SuiteBuildJsonGo))
}

type SuiteBuildJsonGo struct {
	suite.Suite
	workDir string
	code    []byte
	reader  []byte
}

func (this *SuiteBuildJsonGo) SetupSuite() {
	this.workDir = testdata.ChangeWorkDir()
	this.code = []byte(`package sheeter

type RealData struct {
	S     S     ` + "`json:\"S\"`" + `
	Name0 int64 ` + "`json:\"name0\"`" + `
}

type S struct {
	A     []A  ` + "`json:\"A\"`" + `
	Name1 bool ` + "`json:\"name1\"`" + `
}

type A struct {
	Name2 int64  ` + "`json:\"name2\"`" + `
	Name3 string ` + "`json:\"name3\"`" + `
}
`)
	this.reader = []byte(`// generated by sheeter, DO NOT EDIT.

package sheeter

import "encoding/json"

type RealDataReader map[string]RealData

func (this *RealDataReader) JsonFileName() string {
	return "realData.json"
}

func (this *RealDataReader) FromJson(data []byte) error {
	return json.Unmarshal(data, this)
}
`)
}

func (this *SuiteBuildJsonGo) TearDownSuite() {
	_ = os.RemoveAll(pathSchema)
	_ = os.RemoveAll(pathJsonGo)
	testdata.RestoreWorkDir(this.workDir)
}

func (this *SuiteBuildJsonGo) target() *Content {
	target := &Content{
		LineOfField: 1,
		LineOfLayer: 2,
		LineOfNote:  3,
		Excel:       filepath.Join(testdata.RootPath, testdata.ExcelNameReal),
		Sheet:       testdata.SheetName,
	}
	return target
}

func (this *SuiteBuildJsonGo) TestWriteJsonGo() {
	target := this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), buildLayout(target))
	assert.Nil(this.T(), writeSchema(target))
	assert.Nil(this.T(), writeJsonGo(target))
	testdata.CompareFile(this.T(), target.JsonGoPath(), this.code)
	target.close()

	target = this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), buildLayout(target))
	assert.Nil(this.T(), writeSchema(target))
	target.Excel = testdata.UnknownStr
	assert.NotNil(this.T(), writeJsonGo(target))
	target.close()

	target = this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), buildLayout(target))
	assert.Nil(this.T(), writeSchema(target))
	target.Sheet = testdata.UnknownStr
	assert.NotNil(this.T(), writeJsonGo(target))
	target.close()
}

func (this *SuiteBuildJsonGo) TestWriteJsonGoReader() {
	target := this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), buildLayout(target))
	assert.Nil(this.T(), writeSchema(target))
	assert.Nil(this.T(), writeJsonGoReader(target))
	testdata.CompareFile(this.T(), target.JsonGoReaderPath(), this.reader)
	target.close()

	target = this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), buildLayout(target))
	assert.Nil(this.T(), writeSchema(target))
	target.Excel = testdata.UnknownStr
	assert.NotNil(this.T(), writeJsonGoReader(target))
	target.close()

	target = this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), buildLayout(target))
	assert.Nil(this.T(), writeSchema(target))
	target.Sheet = testdata.UnknownStr
	assert.NotNil(this.T(), writeJsonGoReader(target))
	target.close()
}
