package builds

import (
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"

	"github.com/yinweli/Sheeter/internal"
	"github.com/yinweli/Sheeter/internal/fields"
	"github.com/yinweli/Sheeter/internal/layouts"
	"github.com/yinweli/Sheeter/internal/mixeds"
	"github.com/yinweli/Sheeter/testdata"
)

func TestGenerateJson(t *testing.T) {
	suite.Run(t, new(SuiteGenerateJson))
}

type SuiteGenerateJson struct {
	suite.Suite
	workDir string
}

func (this *SuiteGenerateJson) SetupSuite() {
	this.workDir = testdata.ChangeWorkDir()
}

func (this *SuiteGenerateJson) TearDownSuite() {
	_ = os.RemoveAll(internal.PathJson)
	testdata.RestoreWorkDir(this.workDir)
}

func (this *SuiteGenerateJson) target() *RuntimeStruct {
	target := &RuntimeStruct{
		Mixed: mixeds.NewMixed("test", "data"),
		Type: &layouts.Type{
			Excel:  "test",
			Sheet:  "data",
			Reader: true,
			Fields: []*layouts.Field{
				{Name: "name1", Note: "note1", Field: &fields.Pkey{}, Alter: "", Array: false},
				{Name: "name2", Note: "note2", Field: &fields.Int{}, Alter: "", Array: false},
				{Name: "name3", Note: "note3", Field: &fields.IntArray{}, Alter: "", Array: false},
				{Name: "name4", Note: "note4", Field: nil, Alter: "Data", Array: false},
				{Name: "name5", Note: "note5", Field: nil, Alter: "Data", Array: true},
			},
		},
	}
	return target
}

func (this *SuiteGenerateJson) TestGenerateJsonCsStruct() {
	data1 := []byte(`// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SheeterJson {
    public partial class TestData {
        // note1
        [JsonProperty("Name1")]
        public long Name1 { get; set; }
        // note2
        [JsonProperty("Name2")]
        public long Name2 { get; set; }
        // note3
        [JsonProperty("Name3")]
        public long[] Name3 { get; set; }
        // note4
        [JsonProperty("Name4")]
        public Data Name4 { get; set; }
        // note5
        [JsonProperty("Name5")]
        public Data[] Name5 { get; set; }
    }

    public partial class TestDataStorer {
        public Dictionary<long, TestData> Datas = new Dictionary<long, TestData>(); 
    }
}
`)
	data2 := []byte(`// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SheeterJson {
    public partial class TestData {
        // note1
        [JsonProperty("Name1")]
        public long Name1 { get; set; }
        // note2
        [JsonProperty("Name2")]
        public long Name2 { get; set; }
        // note3
        [JsonProperty("Name3")]
        public long[] Name3 { get; set; }
        // note4
        [JsonProperty("Name4")]
        public Data Name4 { get; set; }
        // note5
        [JsonProperty("Name5")]
        public Data[] Name5 { get; set; }
    }
}
`)

	target := this.target()
	assert.Nil(this.T(), generateJsonCsStruct(target))
	testdata.CompareFile(this.T(), target.JsonCsStructPath(), data1)

	target = this.target()
	target.Reader = false
	assert.Nil(this.T(), generateJsonCsStruct(target))
	testdata.CompareFile(this.T(), target.JsonCsStructPath(), data2)
}

func (this *SuiteGenerateJson) TestGenerateJsonCsReader() {
	data := []byte(`// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;

namespace SheeterJson {
    public partial class TestDataReader {
        public static string FileName() {
            return "testData.json";
        }

        public bool FromPath(string path) {
            return FromData(File.ReadAllText(Path.Combine(path, FileName())));
        }

        public bool FromData(string data) {
            Datas = JsonConvert.DeserializeObject<TestDataStorer>(data);
            return Datas != null;
        }

        public long[] MergePath(params string[] path) {
            var repeats = new List<long>();

            foreach (var itor in path) {
                try {
                    repeats.AddRange(MergeData(File.ReadAllText(Path.Combine(itor, FileName()))));
                } catch {
                    // do nothing
                }
            }

            return repeats.ToArray();
        }

        public long[] MergeData(string data) {
            var repeats = new List<long>();
            var tmpl = JsonConvert.DeserializeObject<TestDataStorer>(data);

            if (tmpl == null)
                return repeats.ToArray();

            if (Datas == null)
                Datas = new TestDataStorer();

            foreach (var itor in tmpl.Datas) {
                if (Data.ContainsKey(itor.Key) == false)
                    Data[itor.Key] = itor.Value;
                else
                    repeats.Add(itor.Key);
            }

            return repeats.ToArray();
        }

        public IDictionary<long, TestData> Data {
            get {
                return Datas.Datas;
            }
        }

        private TestDataStorer Datas = null;
    }
}
`)

	target := this.target()
	assert.Nil(this.T(), generateJsonCsReader(target))
	testdata.CompareFile(this.T(), target.JsonCsReaderPath(), data)
}

func (this *SuiteGenerateJson) TestGenerateJsonGoStruct() {
	data1 := []byte(`// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

type TestData struct {
	// note1
	Name1 int64 ` + "`json:\"Name1\"`" + `
	// note2
	Name2 int64 ` + "`json:\"Name2\"`" + `
	// note3
	Name3 []int64 ` + "`json:\"Name3\"`" + `
	// note4
	Name4 Data ` + "`json:\"Name4\"`" + `
	// note5
	Name5 []Data ` + "`json:\"Name5\"`" + `
}

type TestDataStorer struct {
	Datas map[int64]TestData
}
`)
	data2 := []byte(`// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

type TestData struct {
	// note1
	Name1 int64 ` + "`json:\"Name1\"`" + `
	// note2
	Name2 int64 ` + "`json:\"Name2\"`" + `
	// note3
	Name3 []int64 ` + "`json:\"Name3\"`" + `
	// note4
	Name4 Data ` + "`json:\"Name4\"`" + `
	// note5
	Name5 []Data ` + "`json:\"Name5\"`" + `
}
`)

	target := this.target()
	assert.Nil(this.T(), generateJsonGoStruct(target))
	testdata.CompareFile(this.T(), target.JsonGoStructPath(), data1)

	target = this.target()
	target.Reader = false
	assert.Nil(this.T(), generateJsonGoStruct(target))
	testdata.CompareFile(this.T(), target.JsonGoStructPath(), data2)
}

func (this *SuiteGenerateJson) TestGenerateJsonGoReader() {
	data := []byte(`// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

type TestDataReader struct {
	*TestDataStorer
}

func (this *TestDataReader) FileName() string {
	return "testData.json"
}

func (this *TestDataReader) FromPath(path string) error {
	data, err := os.ReadFile(filepath.Join(path, this.FileName()))

	if err != nil {
		return fmt.Errorf("TestDataReader: from path failed: %w", err)
	}

	return this.FromData(data)
}

func (this *TestDataReader) FromData(data []byte) error {
	this.TestDataStorer = &TestDataStorer{
		Datas: map[int64]TestData{},
	}

	if err := json.Unmarshal(data, this.TestDataStorer); err != nil {
		return fmt.Errorf("TestDataReader: from data failed: %w", err)
	}

	return nil
}

func (this *TestDataReader) MergePath(path ...string) (repeats []int64) {
	for _, itor := range path {
		if data, err := os.ReadFile(filepath.Join(itor, this.FileName())); err == nil {
			repeats = append(repeats, this.MergeData(data)...)
		}
	}

	return repeats
}

func (this *TestDataReader) MergeData(data []byte) (repeats []int64) {
	tmpl := &TestDataStorer{
		Datas: map[int64]TestData{},
	}

	if err := json.Unmarshal(data, tmpl); err != nil {
		return repeats
	}

	if this.TestDataStorer == nil {
		this.TestDataStorer = &TestDataStorer{
			Datas: map[int64]TestData{},
		}
	}

	for k, v := range tmpl.Datas {
		if _, ok := this.TestDataStorer.Datas[k]; ok == false {
			this.TestDataStorer.Datas[k] = v
		} else {
			repeats = append(repeats, k)
		}
	}

	return repeats
}
`)

	target := this.target()
	assert.Nil(this.T(), generateJsonGoReader(target))
	testdata.CompareFile(this.T(), target.JsonGoReaderPath(), data)
}
