package builds

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"

	"github.com/yinweli/Sheeter/testdata"
)

func TestPostJsonCs(t *testing.T) {
	suite.Run(t, new(SuitePostJsonCs))
}

type SuitePostJsonCs struct {
	suite.Suite
	workDir string
	code    []byte
	reader  []byte
}

func (this *SuitePostJsonCs) SetupSuite() {
	code := `namespace realdata
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RealData
    {
        [JsonProperty("S")]
        public S S { get; set; }

        [JsonProperty("name0")]
        public long Name0 { get; set; }
    }

    public partial class S
    {
        [JsonProperty("A")]
        public A[] A { get; set; }

        [JsonProperty("name1")]
        public bool Name1 { get; set; }
    }

    public partial class A
    {
        [JsonProperty("name2")]
        public long Name2 { get; set; }

        [JsonProperty("name3")]
        public string Name3 { get; set; }
    }
}
`
	reader := fmt.Sprintf(`// generated by sheeter, DO NOT EDIT.

namespace realdata {
    using System;
    using System.Collections.Generic;

    using Newtonsoft.Json;

    public partial class RealDataReader {
        public static readonly string JsonPath = "%s";

        public static Dictionary<string, RealData> FromJson(string data) {
            return JsonConvert.DeserializeObject<Dictionary<string, RealData>>(data);
        }
    }
}
`, filepath.Join("json", "realData.json"))

	this.workDir = testdata.ChangeWorkDir()
	this.code = []byte(code)
	this.reader = []byte(reader)
}

func (this *SuitePostJsonCs) TearDownSuite() {
	_ = os.RemoveAll(pathSchema)
	_ = os.RemoveAll(pathJsonCs)
	testdata.RestoreWorkDir(this.workDir)
}

func (this *SuitePostJsonCs) target() *Content {
	target := &Content{
		LineOfField: 1,
		LineOfLayer: 2,
		LineOfNote:  3,
		Excel:       testdata.Path(testdata.ExcelNameReal),
		Sheet:       testdata.SheetName,
	}
	return target
}

func (this *SuitePostJsonCs) TestOutputJsonCsCode() {
	target := this.target()
	assert.Nil(this.T(), Initialize(target))
	assert.Nil(this.T(), OutputJsonSchema(target))
	assert.Nil(this.T(), OutputJsonCsCode(target))
	testdata.CompareFile(this.T(), target.JsonCsPath(), this.code)
	target.Close()

	target = this.target()
	assert.Nil(this.T(), Initialize(target))
	assert.Nil(this.T(), OutputJsonSchema(target))
	target.Excel = testdata.UnknownStr
	assert.NotNil(this.T(), OutputJsonCsCode(target))
	target.Close()

	target = this.target()
	assert.Nil(this.T(), Initialize(target))
	assert.Nil(this.T(), OutputJsonSchema(target))
	target.Sheet = testdata.UnknownStr
	assert.NotNil(this.T(), OutputJsonCsCode(target))
	target.Close()
}

func (this *SuitePostJsonCs) TestOutputJsonCsReader() {
	target := this.target()
	target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
	assert.Nil(this.T(), Initialize(target))
	assert.Nil(this.T(), OutputJsonSchema(target))
	assert.Nil(this.T(), OutputJsonCsReader(target))
	testdata.CompareFile(this.T(), target.JsonCsReaderPath(), this.reader)
	target.Close()

	// 由於linux下檔案名稱幾乎沒有非法字元, 所以這項檢查只針對windows
	if testdata.IsWindows() {
		target = this.target()
		target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
		assert.Nil(this.T(), Initialize(target))
		assert.Nil(this.T(), OutputJsonSchema(target))
		target.Excel = testdata.UnknownStr
		assert.NotNil(this.T(), OutputJsonCsReader(target))
		target.Close()
	} // if

	// 由於linux下檔案名稱幾乎沒有非法字元, 所以這項檢查只針對windows
	if testdata.IsWindows() {
		target = this.target()
		target.excel = testdata.GetTestExcel(testdata.ExcelNameReal)
		assert.Nil(this.T(), Initialize(target))
		assert.Nil(this.T(), OutputJsonSchema(target))
		target.Sheet = testdata.UnknownStr
		assert.NotNil(this.T(), OutputJsonCsReader(target))
		target.Close()
	} // if
}
