// generated by sheeter, DO NOT EDIT.

package sheeter

import (
	"encoding/json"
	"os"
	"strconv"
)

type ExampleDataReader map[int64]ExampleData

var Json = "json/exampleData.json"

func FromJsonFile(path string) (reader ExampleDataReader, err error) {
	data, err := os.ReadFile(path)

	if err != nil {
		return nil, err
	}

	return FromJsonBytes(data)
}

func FromJsonBytes(data []byte) (reader ExampleDataReader, err error) {
	temps := map[string]ExampleData{}

	if err := json.Unmarshal(data, &temps); err != nil {
		return nil, err
	}

	datas := ExampleDataReader{}

	for key, value := range temps {
		k, err := strconv.ParseInt(key, 10, 64)

		if err != nil {
			return nil, err
		}

		datas[k] = value
	}

	return datas, nil
}
