// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

type ExampleData2 struct {
	//
	Reward Reward `json:"Reward"`
	//
	Wallet Wallet `json:"Wallet"`
	// 忽略
	Ignore int32 `json:"Ignore"`
	// 索引
	Key string `json:"Key"`
	// 名稱
	Name string `json:"Name"`
}

type ExampleData2Storer struct {
	Datas map[string]*ExampleData2
}
