// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

type ExampleData struct {
	//
	Reward Reward `json:"Reward"`
	//
	Wallet Wallet `json:"Wallet"`
	// 忽略
	Ignore int64 `json:"Ignore"`
	// 索引
	Key int64 `json:"Key"`
	// 名稱
	Name string `json:"Name"`
}

type ExampleDataStorer struct {
	Datas map[int64]*ExampleData
}
