// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

import (
	"encoding/json"
	"fmt"
)

type ExampleData2Reader struct {
	*ExampleData2Storer
}

func (this *ExampleData2Reader) FileName() FileName {
	return NewFileName("exampleData2", ".json")
}

func (this *ExampleData2Reader) FromData(data []byte) error {
	this.ExampleData2Storer = &ExampleData2Storer{
		Datas: map[string]*ExampleData2{},
	}

	if err := json.Unmarshal(data, this.ExampleData2Storer); err != nil {
		return fmt.Errorf("from data failed: %w", err)
	}

	return nil
}

func (this *ExampleData2Reader) MergeData(data []byte) error {
	tmpl := &ExampleData2Storer{
		Datas: map[string]*ExampleData2{},
	}

	if err := json.Unmarshal(data, tmpl); err != nil {
		return fmt.Errorf("merge data failed: %w", err)
	}

	if this.ExampleData2Storer == nil {
		this.ExampleData2Storer = &ExampleData2Storer{
			Datas: map[string]*ExampleData2{},
		}
	}

	for k, v := range tmpl.Datas {
		if _, ok := this.ExampleData2Storer.Datas[k]; ok {
			return fmt.Errorf("merge data failed: key repeat")
		}

		this.ExampleData2Storer.Datas[k] = v
	}

	return nil
}

func (this *ExampleData2Reader) Clear() {
	this.ExampleData2Storer = nil
}

func (this *ExampleData2Reader) Get(key string) (result *ExampleData2, ok bool) {
	result, ok = this.Datas[key]
	return result, ok
}

func (this *ExampleData2Reader) Keys() (result []string) {
	for itor := range this.Datas {
		result = append(result, itor)
	}

	return result
}

func (this *ExampleData2Reader) Values() (result []*ExampleData2) {
	for _, itor := range this.Datas {
		result = append(result, itor)
	}

	return result
}

func (this *ExampleData2Reader) Count() int {
	return len(this.Datas)
}
