// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

type Wallet struct {
	// 魔晶
	Crystal int32 `json:"Crystal"`
	// 鑽石
	Diamond int32 `json:"Diamond"`
	// 金幣
	Gold int32 `json:"Gold"`
}
