// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterProto

import (
	"fmt"
	"os"
	"path/filepath"

	"google.golang.org/protobuf/proto"
)

type ExampleDataReader struct {
	ExampleDataStorer
}

func (this *ExampleDataReader) FileName() string {
	return "exampleData.pbd"
}

func (this *ExampleDataReader) FromPathFull(path string) error {
	data, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("ExampleDataReader: from path full failed: %w", err)
	}

	return this.FromData(data)
}

func (this *ExampleDataReader) FromPathHalf(path string) error {
	data, err := os.ReadFile(filepath.Join(path, this.FileName()))

	if err != nil {
		return fmt.Errorf("ExampleDataReader: from path half failed: %w", err)
	}

	return this.FromData(data)
}

func (this *ExampleDataReader) FromData(data []byte) error {
	if err := proto.Unmarshal(data, &this.ExampleDataStorer); err != nil {
		return err
	}

	return nil
}
