version: "3"

tasks:
  # 進行程式碼檢查
  lint:
    ignore_error: true
    cmds:
      - task: install
      - task: fmt-sheeter
      - task: fmt-cs
      - task: fmt-yaml
      - task: lint-sheeter

  fmt-sheeter:
    cmds:
      - gofmt -s -w -l .

  fmt-cs:
    cmds:
      - dotnet csharpier .

  fmt-yaml:
    cmds:
      - npx prettier --write "*.yaml" "*.yml" "**/*.yaml" "**/*.yml"

  lint-sheeter:
    cmds:
      - golangci-lint -v run

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 編譯操作手冊
  manual:
    cmds:
      - npm install mdpdf -g
      - rm -f README.pdf
      - mdpdf README.md README.pdf

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - dotnet tool install csharpier -g # 安裝cs格式化工具
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - npm install -g prettier # 安裝yaml格式化工具
