version: "3"

tasks:
  # 程式碼格式化
  lint:
    cmds:
      - task: fmt-sheeter
      - task: fmt-cs
      - task: fmt-yaml
      - task: lint-sheeter

  fmt-sheeter:
    ignore_error: true
    cmds:
      - gofmt -s -w -l .

  fmt-cs:
    ignore_error: true
    cmds:
      - csharpier format .

  fmt-yaml:
    ignore_error: true
    cmds:
      - npx prettier --write "*.yaml" "*.yml" "**/*.yaml" "**/*.yml"

  lint-sheeter:
    ignore_error: true
    cmds:
      - golangci-lint run --color always

  # 單元測試
  test:
    cmds:
      - go test ./... -cover

  # 效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - dotnet tool install csharpier -g # 安裝cs格式化工具
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - npm install -g prettier # 安裝yaml格式化工具
