version: "3"

tasks:
  # 程式碼格式化
  lint:
    ignore_error: true
    cmds:
      - csharpier format .
      - golangci-lint fmt # 執行 gofmt + goimports
      - golangci-lint run --color always
      - npx markdownlint-cli --fix "*.md"
      - npx prettier --write --log-level warn --end-of-line lf '*.yml' '*.yaml' '**/*.yml' '**/*.yaml' || true

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - dotnet tool install csharpier -g # 安裝 cs 格式化工具
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest # 安裝 lint
      - go install golang.org/x/tools/cmd/goimports@latest # 安裝 go 引入排序工具
      - npm install -g markdownlint-cli # 安裝 markdown 格式化工具
      - npm install -g prettier # 安裝 yaml 格式化工具
