version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    cmds:
      - task: fmt-sheeter
      - task: lint-sheeter

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # sheeter程式碼格式化
  fmt-sheeter:
    cmds:
      - gofmt -s -w -l .

  # sheeter程式碼檢查
  lint-sheeter:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint -v run