version: "3"

tasks:
  # 程式碼格式化
  lint:
    ignore_error: true
    cmds:
      - csharpier format .
      - gofmt -s -w -l .
      - goimports -w .
      - golangci-lint run --color always
      - npx markdownlint-cli --fix "*.md"
      - npx prettier --write "*.yaml" "*.yml" "**/*.yaml" "**/*.yml" --end-of-line lf

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - dotnet tool install csharpier -g # 安裝 cs 格式化工具
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝 lint
      - go install golang.org/x/tools/cmd/goimports@latest # 安裝 go 引入排序工具
      - npm install -g prettier # 安裝 yaml 格式化工具
