version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    cmds:
      - gofmt -s -w -l . # 程式碼格式化
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝/更新golangci-lint
      - golangci-lint -v run # 程式碼檢查
  
  # 進行程式碼測試
  test:
    cmds:
      - go test -cover ./...