version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    ignore_error: true
    cmds:
      - task: install
      - task: fmt-sheeter
      - task: fmt-cs
      - task: lint-sheeter

  fmt-sheeter:
    cmds:
      - gofmt -s -w -l .

  fmt-cs:
    cmds:
      - dotnet csharpier .

  lint-sheeter:
    cmds:
      - golangci-lint -v run

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - dotnet tool install csharpier -g # 安裝cs格式化工具