version: '3'

tasks:
  # 進行代碼檢查
  lint:
    cmds:
      - task: install-lint
      - task: fmt
      - golangci-lint -v run
  
  # 進行代碼測試
  test:
    cmds:
      - go test -cover ./...
  
  # 進行代碼格式化
  fmt:
    cmds:
      - gofmt -s -w -l .
  
  # 安裝/更新golangci-lint
  install-lint:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest