// generated by sheeter, DO NOT EDIT.

package sheeter

import (
	"encoding/json"
	"fmt"
	"os"
)

type ExampleDataReader struct {
	Datas map[int64]ExampleData
}

func (this *ExampleDataReader) Json() string {
	return "exampleData.json"
}

func (this *ExampleDataReader) FromJsonFile(path string) error {
	data, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("ExampleDataReader: from json file failed: %w", err)
	}

	return this.FromJsonBytes(data)
}

func (this *ExampleDataReader) FromJsonBytes(data []byte) error {
	datas := map[int64]ExampleData{}

	if err := json.Unmarshal(data, &datas); err != nil {
		return err
	}

	this.Datas = datas
	return nil
}
