// generated by sheeter, DO NOT EDIT.

using Newtonsoft.Json;
using System;
using System.IO;
using System.Collections.Generic;

namespace sheeter {
    public partial class ExampleDataReader {
        public static readonly string Json = "json/exampleData.json";

        public static Dictionary<long, ExampleData> FromJsonFile(string path) {
            return FromJsonString(File.ReadAllText(path));
        }

        public static Dictionary<long, ExampleData> FromJsonString(string data) {
            var temps = JsonConvert.DeserializeObject<Dictionary<string, ExampleData>>(data);

            if (temps == null) {
                return null;
            }

            var datas = new Dictionary<long, ExampleData>();

            foreach(var itor in temps) {
                datas[Convert.ToInt64(itor.Key)] = itor.Value;
            }

            return datas;
        }
    }
}
