package tmpls

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/yinweli/Sheeter/sheeter"
	"github.com/yinweli/Sheeter/sheeter/utils"
)

// Initialize 初始化
func Initialize(cmd *cobra.Command) error {
	flags := cmd.Flags()

	// 如果有設定清理旗標, 就刪除模板檔案
	if flags.Changed(flagClean) {
		if clean, err := flags.GetBool(flagClean); err == nil && clean {
			_ = os.RemoveAll(sheeter.TmplPath)
		} // if
	} // if

	tmpls := []*Tmpl{
		JsonStructCs,
		JsonReaderCs,
		JsonDepotCs,
		JsonStructGo,
		JsonReaderGo,
		JsonDepotGo,
		ProtoSchema,
		ProtoReaderCs,
		ProtoDepotCs,
		ProtoReaderGo,
		ProtoDepotGo,
		EnumSchema,
	}

	// 先嘗試讀取模板檔案, 然後再儲存模板檔案
	// 如果沒有模板檔案的狀況下, 這樣會使用預設的模板字串, 並用此字串建立模板檔案
	// 如果已有模板檔案的狀況下, 這樣會使用模板檔案的模板字串, 並保持模板檔案內容
	for _, itor := range tmpls {
		if err := itor.load(); err != nil {
			return fmt.Errorf("tmpl initialize failed: %w", err)
		} // if

		if err := itor.save(); err != nil {
			return fmt.Errorf("tmpl initialize failed: %w", err)
		} // if
	} // for

	return nil
}

// Tmpl 模板資料
type Tmpl struct {
	Name string // 模板檔名
	Data string // 模板字串
}

// load 讀取模板; 嘗試從模板路徑指向的檔案讀取模板字串, 如果檔案不存在就什麼都不做
func (this *Tmpl) load() error {
	path := this.path()

	if utils.FileExist(path) == false {
		return nil
	} // if

	data, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("%s: tmpl load failed: %w", this.Name, err)
	} // if

	this.Data = string(data)
	return nil
}

// save 儲存模板, 把模板字串儲存到模板路徑指向的檔案
func (this *Tmpl) save() error {
	if err := utils.WriteFile(this.path(), []byte(this.Data)); err != nil {
		return fmt.Errorf("%s: tmpl save failed: %w", this.Name, err)
	} // if

	return nil
}

// path 取得模板路徑
func (this *Tmpl) path() string {
	return filepath.Join(sheeter.TmplPath, this.Name)
}

// HeaderCode 程式碼標頭
const HeaderCode = `// Code generated by {{$.AppName}}. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter
`
