// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: path1Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SheeterEnum {

  /// <summary>Holder for reflection information generated from path1Enum.proto</summary>
  public static partial class Path1EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for path1Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Path1EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wYXRoMUVudW0ucHJvdG8SC3NoZWV0ZXJFbnVtKiwKCVBhdGgxRW51bRIJ",
            "CgVOYW1lMBAAEgkKBU5hbWUxEAESCQoFTmFtZTIQAkIPWg0uO3NoZWV0ZXJF",
            "bnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SheeterEnum.Path1Enum), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Path1Enum {
    /// <summary>
    /// 第0個列舉
    /// </summary>
    [pbr::OriginalName("Name0")] Name0 = 0,
    /// <summary>
    /// 第1個列舉
    /// </summary>
    [pbr::OriginalName("Name1")] Name1 = 1,
    /// <summary>
    /// 第2個列舉
    /// </summary>
    [pbr::OriginalName("Name2")] Name2 = 2,
  }

  #endregion

}

#endregion Designer generated code
