// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: path1Enum.proto

package sheeterEnum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Path1Enum int32

const (
	Path1Enum_Name0 Path1Enum = 0 // 第0個列舉
	Path1Enum_Name1 Path1Enum = 1 // 第1個列舉
	Path1Enum_Name2 Path1Enum = 2 // 第2個列舉
)

// Enum value maps for Path1Enum.
var (
	Path1Enum_name = map[int32]string{
		0: "Name0",
		1: "Name1",
		2: "Name2",
	}
	Path1Enum_value = map[string]int32{
		"Name0": 0,
		"Name1": 1,
		"Name2": 2,
	}
)

func (x Path1Enum) Enum() *Path1Enum {
	p := new(Path1Enum)
	*p = x
	return p
}

func (x Path1Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Path1Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_path1Enum_proto_enumTypes[0].Descriptor()
}

func (Path1Enum) Type() protoreflect.EnumType {
	return &file_path1Enum_proto_enumTypes[0]
}

func (x Path1Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Path1Enum.Descriptor instead.
func (Path1Enum) EnumDescriptor() ([]byte, []int) {
	return file_path1Enum_proto_rawDescGZIP(), []int{0}
}

var File_path1Enum_proto protoreflect.FileDescriptor

var file_path1Enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x61, 0x74, 0x68, 0x31, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x73, 0x68, 0x65, 0x65, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x2a, 0x2c,
	0x0a, 0x09, 0x50, 0x61, 0x74, 0x68, 0x31, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x4e,
	0x61, 0x6d, 0x65, 0x30, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x31, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x10, 0x02, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x3b, 0x73, 0x68, 0x65, 0x65, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_path1Enum_proto_rawDescOnce sync.Once
	file_path1Enum_proto_rawDescData = file_path1Enum_proto_rawDesc
)

func file_path1Enum_proto_rawDescGZIP() []byte {
	file_path1Enum_proto_rawDescOnce.Do(func() {
		file_path1Enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_path1Enum_proto_rawDescData)
	})
	return file_path1Enum_proto_rawDescData
}

var file_path1Enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_path1Enum_proto_goTypes = []interface{}{
	(Path1Enum)(0), // 0: sheeterEnum.Path1Enum
}
var file_path1Enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_path1Enum_proto_init() }
func file_path1Enum_proto_init() {
	if File_path1Enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_path1Enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path1Enum_proto_goTypes,
		DependencyIndexes: file_path1Enum_proto_depIdxs,
		EnumInfos:         file_path1Enum_proto_enumTypes,
	}.Build()
	File_path1Enum_proto = out.File
	file_path1Enum_proto_rawDesc = nil
	file_path1Enum_proto_goTypes = nil
	file_path1Enum_proto_depIdxs = nil
}
