// generated by sheeter, DO NOT EDIT.
protoc --experimental_allow_proto3_optional --proto_path=./schema --csharp_out=./cs ./schema\exampleData.proto
protoc --experimental_allow_proto3_optional --proto_path=./schema --csharp_out=./cs ./schema\item.proto
protoc --experimental_allow_proto3_optional --proto_path=./schema --csharp_out=./cs ./schema\reward.proto
