// generated by sheeter, DO NOT EDIT.
protoc --experimental_allow_proto3_optional --proto_path=./schema --go_out=./codeGo ./schema\exampleData.proto
protoc --experimental_allow_proto3_optional --proto_path=./schema --go_out=./codeGo ./schema\item.proto
protoc --experimental_allow_proto3_optional --proto_path=./schema --go_out=./codeGo ./schema\reward.proto
