// generated by sheeter, DO NOT EDIT.

using System;
using System.IO;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace testdata {
    public partial class Reader {
        public static readonly string Json = "json\testData.json";

        public static Dictionary<long, Struct> FromJsonFile(string path) {
            return FromJson(File.ReadAllText(path));
        }

        public static Dictionary<long, Struct> FromJsonString(string data) {
            var datas = new Dictionary<long, Struct>;

            foreach(var itor in JsonConvert.DeserializeObject<Dictionary<string, Struct>>(data)) {
                datas[Convert.ToInt64(itor.Key)] = itor.Value;
            } // for

            return datas;
        }
    }
}
