// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using System.Collections.Generic;

namespace SheeterJson
{
    public partial class Depot
    {
        public Loader Loader { get; set; }
        public readonly File1DataReader File1Data = new File1DataReader();
        public readonly File2DataReader File2Data = new File2DataReader();
        public readonly Path1DataReader Path1Data = new Path1DataReader();
        public readonly Path2DataReader Path2Data = new Path2DataReader();
        public readonly Path3DataReader Path3Data = new Path3DataReader();
        private readonly List<Reader> Readers = new List<Reader>();

        public Depot()
        {
            Readers.Add(File1Data);
            Readers.Add(File2Data);
            Readers.Add(Path1Data);
            Readers.Add(Path2Data);
            Readers.Add(Path3Data);
        }

        public bool FromData()
        {
            if (Loader == null)
                return false;

            var result = true;

            foreach (var itor in Readers)
            {
                var filename = itor.FileName();
                var data = Loader.Load(filename);

                if (data == null || data.Length == 0)
                    continue;

                var message = itor.FromData(data);

                if (message.Length != 0)
                {
                    result = false;
                    Loader.Error(filename.File, message);
                }
            }

            return result;
        }

        public bool MergeData()
        {
            if (Loader == null)
                return false;

            var result = true;

            foreach (var itor in Readers)
            {
                var filename = itor.FileName();
                var data = Loader.Load(filename);

                if (data == null || data.Length == 0)
                    continue;

                var message = itor.MergeData(data);

                if (message.Length != 0)
                {
                    result = false;
                    Loader.Error(filename.File, message);
                }
            }

            return result;
        }

        public void Clear()
        {
            foreach (var itor in Readers)
            {
                itor.Clear();
            }
        }
    }

    public class FileName
    {
        public FileName(string name, string ext)
        {
            this.name = name;
            this.ext = ext;
        }

        public string Name
        {
            get { return name; }
        }

        public string Ext
        {
            get { return ext; }
        }

        public string File
        {
            get { return name + ext; }
        }

        private readonly string name;
        private readonly string ext;
    }

    public interface Loader
    {
        public void Error(string name, string message);
        public string Load(FileName filename);
    }

    public interface Reader
    {
        public FileName FileName();
        public string FromData(string data);
        public string MergeData(string data);
        public void Clear();
    }
}
