// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SheeterJson
{
    public partial class Reward
    {
        //
        [JsonProperty("Item")]
        public Item[] Item { get; set; }

        // 天金
        [JsonProperty("Atium")]
        public int Atium { get; set; }

        // 魔晶
        [JsonProperty("Crystal")]
        public int Crystal { get; set; }

        // 鑽石
        [JsonProperty("Diamond")]
        public int Diamond { get; set; }

        // 精鐵
        [JsonProperty("FelIron")]
        public int FelIron { get; set; }

        // 金幣
        [JsonProperty("Gold")]
        public int Gold { get; set; }
    }
}
