REM generated by sheeter, DO NOT EDIT.
REM please run this on PowerShell / Windows PowerShell 
REM https://learn.microsoft.com/zh-tw/powershell/scripting/whats-new/what-s-new-in-powershell-73?view=powershell-7.2

mkdir proto\codeGo
protoc --experimental_allow_proto3_optional --proto_path=./proto\schema --go_out=./proto\codeGo ./proto\schema\exampleData.proto
protoc --experimental_allow_proto3_optional --proto_path=./proto\schema --go_out=./proto\codeGo ./proto\schema\item.proto
protoc --experimental_allow_proto3_optional --proto_path=./proto\schema --go_out=./proto\codeGo ./proto\schema\reward.proto
