// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterProto

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

type File1DataReader struct {
	*File1DataStorer
}

func (this *File1DataReader) FileName() FileName {
	return NewFileName("file1Data", ".bytes")
}

func (this *File1DataReader) FromData(data []byte) error {
	this.File1DataStorer = &File1DataStorer{
		Datas: map[int32]*File1Data{},
	}

	if err := proto.Unmarshal(data, this.File1DataStorer); err != nil {
		return fmt.Errorf("from data failed: %w", err)
	}

	return nil
}

func (this *File1DataReader) MergeData(data []byte) error {
	tmpl := &File1DataStorer{
		Datas: map[int32]*File1Data{},
	}

	if err := proto.Unmarshal(data, tmpl); err != nil {
		return fmt.Errorf("merge data failed: %w", err)
	}

	if this.File1DataStorer == nil {
		this.File1DataStorer = &File1DataStorer{
			Datas: map[int32]*File1Data{},
		}
	}

	for k, v := range tmpl.Datas {
		if _, ok := this.File1DataStorer.Datas[k]; ok {
			return fmt.Errorf("merge data failed: key repeat")
		}

		this.File1DataStorer.Datas[k] = v
	}

	return nil
}

func (this *File1DataReader) Clear() {
	this.File1DataStorer = nil
}

func (this *File1DataReader) Get(key int32) (result *File1Data, ok bool) {
	result, ok = this.Datas[key]
	return result, ok
}

func (this *File1DataReader) Keys() (result []int32) {
	for itor := range this.Datas {
		result = append(result, itor)
	}

	return result
}

func (this *File1DataReader) Values() (result []*File1Data) {
	for _, itor := range this.Datas {
		result = append(result, itor)
	}

	return result
}

func (this *File1DataReader) Count() int {
	return len(this.Datas)
}
