// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterProto

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

type Path3DataReader struct {
	*Path3DataStorer
}

func (this *Path3DataReader) DataName() string {
	return "path3Data"
}

func (this *Path3DataReader) DataExt() string {
	return ".bytes"
}

func (this *Path3DataReader) DataFile() string {
	return "path3Data.bytes"
}

func (this *Path3DataReader) FromData(data []byte) error {
	this.Path3DataStorer = &Path3DataStorer{
		Datas: map[int64]*Path3Data{},
	}

	if err := proto.Unmarshal(data, this.Path3DataStorer); err != nil {
		return fmt.Errorf("from data failed: %w", err)
	}

	return nil
}

func (this *Path3DataReader) MergeData(data []byte) error {
	tmpl := &Path3DataStorer{
		Datas: map[int64]*Path3Data{},
	}

	if err := proto.Unmarshal(data, tmpl); err != nil {
		return fmt.Errorf("merge data failed: %w", err)
	}

	if this.Path3DataStorer == nil {
		this.Path3DataStorer = &Path3DataStorer{
			Datas: map[int64]*Path3Data{},
		}
	}

	for k, v := range tmpl.Datas {
		if _, ok := this.Path3DataStorer.Datas[k]; ok {
			return fmt.Errorf("merge data failed: key repeat")
		}

		this.Path3DataStorer.Datas[k] = v
	}

	return nil
}

func (this *Path3DataReader) Clear() {
	this.Path3DataStorer = nil
}

func (this *Path3DataReader) Get(key int64) (result *Path3Data, ok bool) {
	result, ok = this.Datas[key]
	return result, ok
}

func (this *Path3DataReader) Keys() (result []int64) {
	for itor := range this.Datas {
		result = append(result, itor)
	}

	return result
}

func (this *Path3DataReader) Values() (result []*Path3Data) {
	for _, itor := range this.Datas {
		result = append(result, itor)
	}

	return result
}

func (this *Path3DataReader) Count() int {
	return len(this.Datas)
}
