// generated by sheeter, DO NOT EDIT.

using Newtonsoft.Json;

namespace sheeter {
    public partial class Item {
        // note7
        [JsonProperty("Count")]
        public long Count { get; set; }
        // note5
        [JsonProperty("ItemID")]
        public long ItemID { get; set; }
        // note6
        [JsonProperty("Type")]
        public long Type { get; set; }
    }
}
