// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeterJson

type File2Data struct {
	//
	Reward Reward `json:"Reward"`
	// 是否啟用
	Enable bool `json:"Enable"`
	// 忽略
	Ignore int32 `json:"Ignore"`
	// 索引
	Key int32 `json:"Key"`
	// 名稱
	Name string `json:"Name"`
}

type File2DataStorer struct {
	Datas map[int32]*File2Data
}
