// generated by sheeter, DO NOT EDIT.

using Newtonsoft.Json;
using System;
using System.IO;
using System.Collections.Generic;

namespace sheeterJson {
    public partial class ExampleDataReader {
        public static string FileName() {
            return "exampleData.json";
        }

        public bool FromPathFull(string path) {
            return FromData(File.ReadAllText(path));
        }

        public bool FromPathHalf(string path) {
            return FromData(File.ReadAllText(Path.Combine(path, FileName())));
        }

        public bool FromData(string data) {
            Datas = JsonConvert.DeserializeObject<ExampleDataStorer>(data);
            return Datas != null;
        }

        public ExampleDataStorer Datas = null;
    }
}
