// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.IO;
using System.Collections.Generic;

namespace sheeterJson {
    public partial class ExampleDataReader {
        public static string FileName() {
            return "exampleData.json";
        }

        public bool FromPathFull(string path) {
            return FromData(File.ReadAllText(path));
        }

        public bool FromPathHalf(string path) {
            return FromData(File.ReadAllText(Path.Combine(path, FileName())));
        }

        public bool FromData(string data) {
            Datas = JsonConvert.DeserializeObject<ExampleDataStorer>(data);
            return Datas != null;
        }

        public IDictionary<long, ExampleData> Data {
            get {
                return Datas.Datas;
            }
        }

        private ExampleDataStorer Datas = null;
    }
}
