// generated by sheeter, DO NOT EDIT.

using Newtonsoft.Json;
using System;
using System.IO;
using System.Collections.Generic;

namespace sheeter {
    public partial class ExampleDataReader {
        public static readonly string Json = "exampleData.json";

        public static Dictionary<long, ExampleData> FromJsonFile(string path) {
            return FromJsonString(File.ReadAllText(path));
        }

        public static Dictionary<long, ExampleData> FromJsonString(string data) {
            var datas = JsonConvert.DeserializeObject<Dictionary<long, ExampleData>>(data);
            return datas;
        }
    }
}
