// generated by sheeter, DO NOT EDIT.

package testdata

import (
	"encoding/json"
	"os"
	"strconv"
)

type Reader map[int64]Struct

var Json = "json/testData.json"

func FromJsonFile(path string) (reader Reader, err error) {
	data, err := os.ReadFile(path)

	if err != nil {
		return nil, err
	}

	return FromJsonBytes(data)
}

func FromJsonBytes(data []byte) (reader Reader, err error) {
	temps := map[string]Struct{}

	if err := json.Unmarshal(data, &temps); err != nil {
		return nil, err
	}

	datas := Reader{}

	for key, value := range temps {
		k, err := strconv.ParseInt(key, 10, 64)

		if err != nil {
			return nil, err
		}

		datas[k] = value
	}

	return datas, nil
}
