package tmpls

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/yinweli/Sheeter/internal"
	"github.com/yinweli/Sheeter/internal/utils"
)

// Initialize 初始化
func Initialize(cmd *cobra.Command) error {
	flags := cmd.Flags()

	if flags.Changed(flagClean) {
		if clean, err := flags.GetBool(flagClean); err == nil && clean {
			_ = os.RemoveAll(internal.PathTmpl)
		} // if
	} // if

	tmpls := []*Tmpl{
		JsonCsStruct,
		JsonCsReader,
		JsonGoStruct,
		JsonGoReader,
		ProtoSchema,
		ProtoCsReader,
		ProtoGoReader,
		ProtoCsBat,
		ProtoCsSh,
		ProtoGoBat,
		ProtoGoSh,
	}

	for _, itor := range tmpls {
		if err := itor.load(); err != nil {
			return fmt.Errorf("%w", err)
		} // if

		if err := itor.save(); err != nil {
			return fmt.Errorf("%w", err)
		} // if
	} // for

	return nil
}

// Tmpl 模板資料
type Tmpl struct {
	Name string // 模板檔名
	Data string // 模板字串
}

// load 讀取模板
func (this *Tmpl) load() error {
	path := this.path()

	if utils.ExistFile(path) == false {
		return nil
	} // if

	data, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("%s: tmpl load failed: %w", this.Name, err)
	} // if

	this.Data = string(data)
	return nil
}

// save 儲存模板
func (this *Tmpl) save() error {
	if err := utils.WriteFile(this.path(), []byte(this.Data)); err != nil {
		return fmt.Errorf("%s: tmpl save failed: %w", this.Name, err)
	} // if

	return nil
}

// path 取得模板路徑
func (this *Tmpl) path() string {
	return filepath.Join(internal.PathTmpl, this.Name)
}

// TODO: json (cs, go): struct, storer, reader, keeper
// TODO: proto (cs, go): schema, storer, reader, keeper

// JsonCsStruct json-cs結構模板
var JsonCsStruct = &Tmpl{
	Name: internal.FileTmplJsonCsStruct,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

using Newtonsoft.Json;

namespace {{$.Namespace}} {
    public partial class {{$.StructName}} {
{{- range $.Fields}}
        // {{$.FieldNote .}}
        [JsonProperty("{{$.FieldName .}}")]
        public {{$.FieldTypeCs .}} {{$.FieldName .}} { get; set; }
{{- end}}
    }
}
`,
}

// JsonCsReader json-cs讀取器模板
var JsonCsReader = &Tmpl{
	Name: internal.FileTmplJsonCsReader,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

using Newtonsoft.Json;
using System;
using System.IO;
using System.Collections.Generic;

namespace {{$.Namespace}} {
    public partial class {{$.ReaderName}} {
        public static readonly string Json = "{{$.FileJsonDataName}}";

        public static Dictionary<long, {{$.StructName}}> FromJsonFile(string path) {
            return FromJsonString(File.ReadAllText(path));
        }

        public static Dictionary<long, {{$.StructName}}> FromJsonString(string data) {
            var datas = JsonConvert.DeserializeObject<Dictionary<long, {{$.StructName}}>>(data);
            return datas;
        }
    }
}
`,
}

// JsonGoStruct json-go結構模板
var JsonGoStruct = &Tmpl{
	Name: internal.FileTmplJsonGoStruct,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

package {{$.Namespace}}

type {{$.StructName}} struct {
{{- range $.Fields}}
	// {{$.FieldNote .}}
	{{$.FieldName .}} {{$.FieldTypeGo .}} ` + "`json:\"{{$.FieldName .}}\"`" + `
{{- end}}
}
`,
}

// JsonGoReader json-go讀取器模板
var JsonGoReader = &Tmpl{
	Name: internal.FileTmplJsonGoReader,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

package {{$.Namespace}}

import (
	"encoding/json"
	"fmt"
	"os"
)

type {{$.ReaderName}} struct {
	Datas map[int64]{{$.StructName}}
}

func (this *{{$.ReaderName}}) Json() string {
	return "{{$.FileJsonDataName}}"
}

func (this *{{$.ReaderName}}) FromJsonFile(path string) error {
	data, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("{{$.ReaderName}}: from json file failed: %w", err)
	}

	return this.FromJsonBytes(data)
}

func (this *{{$.ReaderName}}) FromJsonBytes(data []byte) error {
	datas := map[int64]{{$.StructName}}{}

	if err := json.Unmarshal(data, &datas); err != nil {
		return err
	}

	this.Datas = datas
	return nil
}
`,
}

// ProtoSchema proto架構模板
var ProtoSchema = &Tmpl{
	Name: internal.FileTmplProtoSchema,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

syntax = "proto3";
package {{$.Namespace}};
option go_package = ".;{{$.Namespace}}";

{{- range $.Depend}}
import '{{$.ProtoDepend .}}';
{{- end}}

message {{$.StructName}} {
{{- range $i, $f := $.Fields}}
  {{$.FieldTypeProto .}} {{$.FieldName .}} = {{$.Add $i 1}}; // {{$.FieldNote .}}
{{- end}}
}

message {{$.ReaderName}} {
  map<int64, {{$.StructName}}> Datas = 1;
}
`,
}

// ProtoCsReader proto-cs讀取器模板
var ProtoCsReader = &Tmpl{
	Name: internal.FileTmplProtoCsReader,
	Data: "", // TODO: proto-cs讀取器模板
}

// ProtoGoReader proto-go讀取器模板
var ProtoGoReader = &Tmpl{
	Name: internal.FileTmplProtoGoReader,
	Data: "", // TODO: proto-go讀取器模板
}

// ProtoCsBat proto-cs-bat模板
var ProtoCsBat = &Tmpl{
	Name: internal.FileTmplProtoCsBat,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.PathProtoSchema}} --csharp_out=./{{.PathProtoCs}} ./{{.FileProtoSchemaRelative}}
{{- end}}
`,
}

// ProtoCsSh proto-cs-sh模板
var ProtoCsSh = &Tmpl{
	Name: internal.FileTmplProtoCsSh,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.PathProtoSchema}} --csharp_out=./{{.PathProtoCs}} ./{{.FileProtoSchemaRelative}}
{{- end}}
`,
}

// ProtoGoBat proto-go-bat模板
var ProtoGoBat = &Tmpl{
	Name: internal.FileTmplProtoGoBat,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.PathProtoSchema}} --go_out=./{{.PathProtoGo}} ./{{.FileProtoSchemaRelative}}
{{- end}}
`,
}

// ProtoGoSh proto-go-sh模板
var ProtoGoSh = &Tmpl{
	Name: internal.FileTmplProtoGoSh,
	Data: `// generated by {{$.AppName}}, DO NOT EDIT.

{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.PathProtoSchema}} --go_out=./{{.PathProtoGo}} ./{{.FileProtoSchemaRelative}}
{{- end}}
`,
}
