package tmpls

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/yinweli/Sheeter/internal"
	"github.com/yinweli/Sheeter/internal/utils"
)

// Initialize 初始化
func Initialize(cmd *cobra.Command) error {
	flags := cmd.Flags()

	if flags.Changed(flagClean) {
		if clean, err := flags.GetBool(flagClean); err == nil && clean {
			_ = os.RemoveAll(internal.TmplPath)
		} // if
	} // if

	tmpls := []*Tmpl{
		JsonCsStruct,
		JsonCsReader,
		JsonGoStruct,
		JsonGoReader,
		ProtoSchema,
		ProtoCsReader,
		ProtoGoReader,
		ProtoCsBat,
		ProtoCsSh,
		ProtoGoBat,
		ProtoGoSh,
	}

	for _, itor := range tmpls {
		if err := itor.load(); err != nil {
			return fmt.Errorf("tmpl initialize failed: %w", err)
		} // if

		if err := itor.save(); err != nil {
			return fmt.Errorf("tmpl initialize failed: %w", err)
		} // if
	} // for

	return nil
}

// Tmpl 模板資料
type Tmpl struct {
	Name string // 模板檔名
	Data string // 模板字串
}

// load 讀取模板
func (this *Tmpl) load() error {
	path := this.path()

	if utils.ExistFile(path) == false {
		return nil
	} // if

	data, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("%s: tmpl load failed: %w", this.Name, err)
	} // if

	this.Data = string(data)
	return nil
}

// save 儲存模板
func (this *Tmpl) save() error {
	if err := utils.WriteFile(this.path(), []byte(this.Data)); err != nil {
		return fmt.Errorf("%s: tmpl save failed: %w", this.Name, err)
	} // if

	return nil
}

// path 取得模板路徑
func (this *Tmpl) path() string {
	return filepath.Join(internal.TmplPath, this.Name)
}

// HeaderCode 程式碼標頭
const HeaderCode = `// Code generated by {{$.AppName}}. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter
`

// HeaderBat 批次檔標頭
const HeaderBat = `REM Code generated by {{$.AppName}}. DO NOT EDIT.
REM Sheeter: https://github.com/yinweli/Sheeter
`

// HeaderSh 腳本標頭
const HeaderSh = `# Code generated by {{$.AppName}}. DO NOT EDIT.
# Sheeter: https://github.com/yinweli/Sheeter
`

// JsonCsStruct json-cs結構模板
var JsonCsStruct = &Tmpl{
	Name: internal.TmplJsonCsStructFile,
	Data: HeaderCode + `
using Newtonsoft.Json;
using System.Collections.Generic;

namespace {{$.JsonNamespace $.SimpleNamespace | $.FirstUpper}} {
    public partial class {{$.StructName}} {
{{- range $.Fields}}
        // {{$.FieldNote .}}
        [JsonProperty("{{$.FieldName .}}")]
        public {{$.FieldTypeCs .}} {{$.FieldName .}} { get; set; }
{{- end}}
    }
{{- if $.Reader}}

    public partial class {{$.StorerName}} {
        public Dictionary<{{$.PkeyTypeCs}}, {{$.StructName}}> {{$.StorerDatas}} = new Dictionary<{{$.PkeyTypeCs}}, {{$.StructName}}>(); 
    }
{{- end}}
}
`,
}

// JsonCsReader json-cs讀取器模板
var JsonCsReader = &Tmpl{
	Name: internal.TmplJsonCsReaderFile,
	Data: HeaderCode + `
using Newtonsoft.Json;
using System.Collections.Generic;

namespace {{$.JsonNamespace $.SimpleNamespace | $.FirstUpper}} {
    public partial class {{$.ReaderName}} {
        public string DataName() {
            return "{{$.JsonDataName}}";
        }

        public string DataExt() {
            return "{{$.JsonDataExt}}";
        }

        public string DataFile() {
            return "{{$.JsonDataFile}}";
        }

        public bool FromData(string data) {
            Datas = JsonConvert.DeserializeObject<{{$.StorerName}}>(data);
            return Datas != null;
        }

        public {{$.PkeyTypeCs}}[] MergeData(string data) {
            var repeats = new List<{{$.PkeyTypeCs}}>();
            var tmpl = JsonConvert.DeserializeObject<{{$.StorerName}}>(data);

            if (tmpl == null)
                return repeats.ToArray();

            if (Datas == null)
                Datas = new {{$.StorerName}}();

            foreach (var itor in tmpl.{{$.StorerDatas}}) {
                if (Data.ContainsKey(itor.Key) == false)
                    Data[itor.Key] = itor.Value;
                else
                    repeats.Add(itor.Key);
            }

            return repeats.ToArray();
        }

        public IDictionary<{{$.PkeyTypeCs}}, {{$.StructName}}> Data {
            get {
                return Datas.{{$.StorerDatas}};
            }
        }

        private {{$.StorerName}} Datas = null;
    }
}
`,
}

// JsonGoStruct json-go結構模板
var JsonGoStruct = &Tmpl{
	Name: internal.TmplJsonGoStructFile,
	Data: HeaderCode + `
package {{$.JsonNamespace $.SimpleNamespace}}

type {{$.StructName}} struct {
{{- range $.Fields}}
	// {{$.FieldNote .}}
	{{$.FieldName .}} {{$.FieldTypeGo .}} ` + "`json:\"{{$.FieldName .}}\"`" + `
{{- end}}
}
{{- if $.Reader}}

type {{$.StorerName}} struct {
	{{$.StorerDatas}} map[{{$.PkeyTypeGo}}]{{$.StructName}}
}
{{- end}}
`,
}

// JsonGoReader json-go讀取器模板
var JsonGoReader = &Tmpl{
	Name: internal.TmplJsonGoReaderFile,
	Data: HeaderCode + `
package {{$.JsonNamespace $.SimpleNamespace}}

import (
	"encoding/json"
	"fmt"
)

type {{$.ReaderName}} struct {
	*{{$.StorerName}}
}

func (this *{{$.ReaderName}}) DataName() string {
	return "{{$.JsonDataName}}"
}

func (this *{{$.ReaderName}}) DataExt() string {
	return "{{$.JsonDataExt}}"
}

func (this *{{$.ReaderName}}) DataFile() string {
	return "{{$.JsonDataFile}}"
}

func (this *{{$.ReaderName}}) FromData(data []byte) error {
	this.{{$.StorerName}} = &{{$.StorerName}}{
		{{$.StorerDatas}}: map[{{$.PkeyTypeGo}}]{{$.StructName}}{},
	}

	if err := json.Unmarshal(data, this.{{$.StorerName}}); err != nil {
		return fmt.Errorf("{{$.ReaderName}}: from data failed: %w", err)
	}

	return nil
}

func (this *{{$.ReaderName}}) MergeData(data []byte) (repeats []{{$.PkeyTypeGo}}) {
	tmpl := &{{$.StorerName}}{
		{{$.StorerDatas}}: map[{{$.PkeyTypeGo}}]{{$.StructName}}{},
	}

	if err := json.Unmarshal(data, tmpl); err != nil {
		return repeats
	}

	if this.{{$.StorerName}} == nil {
		this.{{$.StorerName}} = &{{$.StorerName}}{
			{{$.StorerDatas}}: map[{{$.PkeyTypeGo}}]{{$.StructName}}{},
		}
	}

	for k, v := range tmpl.{{$.StorerDatas}} {
		if _, ok := this.{{$.StorerName}}.{{$.StorerDatas}}[k]; ok == false {
			this.{{$.StorerName}}.{{$.StorerDatas}}[k] = v
		} else {
			repeats = append(repeats, k)
		}
	}

	return repeats
}
`,
}

// ProtoSchema proto架構模板
var ProtoSchema = &Tmpl{
	Name: internal.TmplProtoSchemaFile,
	Data: HeaderCode + `
syntax = "proto3";
package {{$.ProtoNamespace $.SimpleNamespace}};
option go_package = ".;{{$.ProtoNamespace $.SimpleNamespace}}";

{{- range $.Depend}}
import '{{$.ProtoDepend .}}';
{{- end}}

message {{$.StructName}} {
{{- range $i, $f := $.Fields}}
  {{$.FieldTypeProto .}} {{$.FieldName .}} = {{$.Add $i 1}}; // {{$.FieldNote .}}
{{- end}}
}
{{- if $.Reader}}

message {{$.StorerName}} {
  map<{{$.PkeyTypeProto}}, {{$.StructName}}> Datas = 1;
}
{{- end}}
`,
}

// ProtoCsReader proto-cs讀取器模板
var ProtoCsReader = &Tmpl{
	Name: internal.TmplProtoCsReaderFile,
	Data: HeaderCode + `
using System.Collections.Generic;

namespace {{$.ProtoNamespace $.SimpleNamespace | $.FirstUpper}} {
    public partial class {{$.ReaderName}} {
        public string DataName() {
            return "{{$.ProtoDataName}}";
        }

        public string DataExt() {
            return "{{$.ProtoDataExt}}";
        }

        public string DataFile() {
            return "{{$.ProtoDataFile}}";
        }

        public bool FromData(byte[] data) {
            Datas = {{$.StorerName}}.Parser.ParseFrom(data);
            return Datas != null;
        }

        public {{$.PkeyTypeCs}}[] MergeData(byte[] data) {
            var repeats = new List<{{$.PkeyTypeCs}}>();
            var tmpl = {{$.StorerName}}.Parser.ParseFrom(data);

            if (tmpl == null)
                return repeats.ToArray();

            if (Datas == null)
                Datas = new {{$.StorerName}}();

            foreach (var itor in tmpl.{{$.StorerDatas}}) {
                if (Data.ContainsKey(itor.Key) == false)
                    Data[itor.Key] = itor.Value;
                else
                    repeats.Add(itor.Key);
            }

            return repeats.ToArray();
        }

        public IDictionary<{{$.PkeyTypeCs}}, {{$.StructName}}> Data {
            get {
                return Datas.{{$.StorerDatas}};
            }
        }

        private {{$.StorerName}} Datas = null;
    }
}
`,
}

// ProtoGoReader proto-go讀取器模板
var ProtoGoReader = &Tmpl{
	Name: internal.TmplProtoGoReaderFile,
	Data: HeaderCode + `
package {{$.ProtoNamespace $.SimpleNamespace}}

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

type {{$.ReaderName}} struct {
	*{{$.StorerName}}
}

func (this *{{$.ReaderName}}) DataName() string {
	return "{{$.ProtoDataName}}"
}

func (this *{{$.ReaderName}}) DataExt() string {
	return "{{$.ProtoDataExt}}"
}

func (this *{{$.ReaderName}}) DataFile() string {
	return "{{$.ProtoDataFile}}"
}

func (this *{{$.ReaderName}}) FromData(data []byte) error {
	this.{{$.StorerName}} = &{{$.StorerName}}{
		Datas: map[{{$.PkeyTypeGo}}]*{{$.StructName}}{},
	}

	if err := proto.Unmarshal(data, this.{{$.StorerName}}); err != nil {
		return fmt.Errorf("{{$.ReaderName}}: from data failed: %w", err)
	}

	return nil
}

func (this *{{$.ReaderName}}) MergeData(data []byte) (repeats []{{$.PkeyTypeGo}}) {
	tmpl := &{{$.StorerName}}{
		{{$.StorerDatas}}: map[{{$.PkeyTypeGo}}]*{{$.StructName}}{},
	}

	if err := proto.Unmarshal(data, tmpl); err != nil {
		return repeats
	}

	if this.{{$.StorerName}} == nil {
		this.{{$.StorerName}} = &{{$.StorerName}}{
			{{$.StorerDatas}}: map[{{$.PkeyTypeGo}}]*{{$.StructName}}{},
		}
	}

	for k, v := range tmpl.{{$.StorerDatas}} {
		if _, ok := this.{{$.StorerName}}.{{$.StorerDatas}}[k]; ok == false {
			this.{{$.StorerName}}.{{$.StorerDatas}}[k] = v
		} else {
			repeats = append(repeats, k)
		}
	}

	return repeats
}
`,
}

// ProtoCsBat proto-cs-bat模板
var ProtoCsBat = &Tmpl{
	Name: internal.TmplProtoCsBatFile,
	Data: HeaderBat + `
mkdir {{.ProtoCsPath}}
{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.ProtoSchemaPath}} --csharp_out=./{{.ProtoCsPath}} ./{{.ProtoPath}}
{{- end}}
`,
}

// ProtoCsSh proto-cs-sh模板
var ProtoCsSh = &Tmpl{
	Name: internal.TmplProtoCsShFile,
	Data: HeaderSh + `
mkdir {{.ProtoCsPath}}
{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.ProtoSchemaPath}} --csharp_out=./{{.ProtoCsPath}} ./{{.ProtoPath}}
{{- end}}
`,
}

// ProtoGoBat proto-go-bat模板
var ProtoGoBat = &Tmpl{
	Name: internal.TmplProtoGoBatFile,
	Data: HeaderBat + `
mkdir {{.ProtoGoPath}}
{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.ProtoSchemaPath}} --go_out=./{{.ProtoGoPath}} ./{{.ProtoPath}}
{{- end}}
`,
}

// ProtoGoSh proto-go-sh模板
var ProtoGoSh = &Tmpl{
	Name: internal.TmplProtoGoShFile,
	Data: HeaderSh + `
mkdir {{.ProtoGoPath}}
{{- range $.Struct}}
protoc --experimental_allow_proto3_optional --proto_path=./{{.ProtoSchemaPath}} --go_out=./{{.ProtoGoPath}} ./{{.ProtoPath}}
{{- end}}
`,
}
