// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SheeterJson
{
    public partial class ExampleData
    {
        //
        [JsonProperty("Reward")]
        public Reward Reward { get; set; }

        //
        [JsonProperty("Wallet")]
        public Wallet Wallet { get; set; }

        // 忽略
        [JsonProperty("Ignore")]
        public int Ignore { get; set; }

        // 索引
        [JsonProperty("Key")]
        public System.Int32 Key { get; set; }

        // 名稱
        [JsonProperty("Name")]
        public string Name { get; set; }
    }

    public partial class ExampleDataStorer
    {
        public Dictionary<System.Int32, ExampleData> Datas =
            new Dictionary<System.Int32, ExampleData>();
    }
}
