// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SheeterJson
{
    public partial class Reward
    {
        //
        [JsonProperty("Item")]
        public Item[] Item { get; set; }

        // 獎勵描述
        [JsonProperty("Desc")]
        public string Desc { get; set; }
    }
}
