package codes

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/yinweli/Sheeter/internal"
	"github.com/yinweli/Sheeter/internal/utils"
)

// Initialize 初始化
func Initialize(cmd *cobra.Command) error {
	flags := cmd.Flags()

	if flags.Changed(flagClean) {
		if clean, err := flags.GetBool(flagClean); err == nil && clean {
			_ = os.RemoveAll(internal.PathCode)
		} // if
	} // if

	if err := JsonCsReader.load(); err != nil {
		return fmt.Errorf("%w", err)
	} // if

	if err := JsonCsReader.save(); err != nil {
		return fmt.Errorf("%w", err)
	} // if

	if err := JsonGoReader.load(); err != nil {
		return fmt.Errorf("%w", err)
	} // if

	if err := JsonGoReader.save(); err != nil {
		return fmt.Errorf("%w", err)
	} // if

	return nil
}

// Code 程式碼資料
type Code struct {
	Name string // 程式碼檔名
	Code string // 程式碼字串
}

// load 讀取程式碼
func (this *Code) load() error {
	path := this.path()

	if utils.ExistFile(path) == false {
		return nil
	} // if

	code, err := os.ReadFile(path)

	if err != nil {
		return fmt.Errorf("%s: code load failed: %w", this.Name, err)
	} // if

	this.Code = string(code)
	return nil
}

// save 儲存程式碼
func (this *Code) save() error {
	if err := utils.WriteFile(this.path(), []byte(this.Code)); err != nil {
		return fmt.Errorf("%s: code save failed: %w", this.Name, err)
	} // if

	return nil
}

// path 取得程式碼路徑
func (this *Code) path() string {
	return filepath.Join(internal.PathCode, this.Name)
}

// JsonCsStruct json-cs結構程式碼
var JsonCsStruct = Code{
	Name: internal.FileCodeJsonCsStruct,
	Code: `// generated by {{$.AppName}}, DO NOT EDIT.

using Newtonsoft.Json;

namespace {{$.Namespace}} {
    public partial {{.StructName}} {
    
    }
}
`,
}

// JsonCsReader json-cs讀取器程式碼
var JsonCsReader = Code{
	Name: internal.FileCodeJsonCsReader,
	Code: `// generated by {{$.AppName}}, DO NOT EDIT.

using Newtonsoft.Json;
using System;
using System.IO;
using System.Collections.Generic;

namespace {{$.Namespace}} {
    public partial class {{.ReaderName}} {
        public static readonly string Json = "{{.CodePath .FileJson}}";

        public static Dictionary<long, {{.StructName}}> FromJsonFile(string path) {
            return FromJsonString(File.ReadAllText(path));
        }

        public static Dictionary<long, {{.StructName}}> FromJsonString(string data) {
            var temps = JsonConvert.DeserializeObject<Dictionary<string, {{.StructName}}>>(data);

            if (temps == null) {
                return null;
            }

            var datas = new Dictionary<long, {{.StructName}}>;

            foreach(var itor in temps) {
                datas[Convert.ToInt64(itor.Key)] = itor.Value;
            }

            return datas;
        }
    }
}
`,
}

// JsonGoReader json-go讀取器程式碼
var JsonGoReader = Code{
	Name: internal.FileCodeJsonGoReader,
	Code: `// generated by {{$.AppName}}, DO NOT EDIT.

package {{$.Namespace}}

import (
	"encoding/json"
	"os"
	"strconv"
)

type {{.ReaderName}} map[int64]{{.StructName}}

var Json = "{{.CodePath .FileJson}}"

func FromJsonFile(path string) (reader {{.ReaderName}}, err error) {
	data, err := os.ReadFile(path)

	if err != nil {
		return nil, err
	}

	return FromJsonBytes(data)
}

func FromJsonBytes(data []byte) (reader {{.ReaderName}}, err error) {
	temps := map[string]{{.StructName}}{}

	if err := json.Unmarshal(data, &temps); err != nil {
		return nil, err
	}

	datas := {{.ReaderName}}{}

	for key, value := range temps {
		k, err := strconv.ParseInt(key, 10, 64)

		if err != nil {
			return nil, err
		}

		datas[k] = value
	}

	return datas, nil
}
`,
}
