name: build

on:
  push:
    tags:
      - "v*"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: [lint, test]
    strategy:
      matrix:
        include:
          - artifacts-name: linux-amd64
            goos: linux
            goarch: amd64
            compress-cmd: tar -czf sheeter-linux-amd64.tar.gz -C sheeter .
            compress-file: sheeter-linux-amd64.tar.gz
          - artifacts-name: darwin-amd64
            goos: darwin
            goarch: amd64
            compress-cmd: tar -czf sheeter-darwin-amd64.tar.gz -C sheeter .
            compress-file: sheeter-darwin-amd64.tar.gz
          - artifacts-name: windows-amd64
            goos: windows
            goarch: amd64
            compress-cmd: 7z a -tzip sheeter-windows-amd64.zip sheeter/*
            compress-file: sheeter-windows-amd64.zip
    name: build ${{ matrix.artifacts-name }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache: true
      - name: build
        shell: bash
        run: |
          mkdir -p sheeter/excel
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o sheeter/ -ldflags="-s -w" cmd/sheeter/*.go
          cp README.md sheeter/
          cp support/example/config.yaml sheeter/
          cp support/example/build.bat sheeter/
          cp support/example/excel/example.xlsx sheeter/excel/
      - name: compress
        shell: bash
        run: ${{ matrix.compress-cmd }}
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.compress-file }}
