name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ubuntu-latest | go 1.25.x | proto 3.x
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache: true
      - name: setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup protoc-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
