// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Sheeter
{
    using Data_ = VerifyData;
    using Key_ = Int32;
    using Store_ = Dictionary<Int32, VerifyData>;

    /// <summary>
    /// verify.xlsx#Data
    /// </summary>
    public partial class VerifyData
    {
        /// <summary>
        /// duration
        /// </summary>
        [JsonProperty("Duration")]
        public String Duration { get; set; }

        /// <summary>
        /// float
        /// </summary>
        [JsonProperty("Float")]
        public Single Float { get; set; }

        /// <summary>
        /// note1
        /// </summary>
        [JsonProperty("Name1")]
        public Int32 Name1 { get; set; }

        /// <summary>
        /// note2
        /// </summary>
        [JsonProperty("Name2")]
        public Int32 Name2 { get; set; }

        /// <summary>
        /// note3
        /// </summary>
        [JsonProperty("Name3")]
        public Int32 Name3 { get; set; }

        /// <summary>
        /// note4
        /// </summary>
        [JsonProperty("Name4")]
        public Int32 Name4 { get; set; }

        /// <summary>
        /// note5
        /// </summary>
        [JsonProperty("Name5")]
        public Int32 Name5 { get; set; }

        /// <summary>
        /// ratio
        /// </summary>
        [JsonProperty("Ratio")]
        public String Ratio { get; set; }

        /// <summary>
        /// space
        /// </summary>
        [JsonProperty("Space")]
        public Int32[] Space { get; set; }
    }

    /// <summary>
    /// verify.xlsx#Data
    /// </summary>
    public partial class VerifyDataReader : Reader
    {
        /// <summary>
        /// 取得檔名物件
        /// </summary>
        public FileName FileName()
        {
            return new FileName("verifyData", ".json");
        }

        /// <summary>
        /// 讀取資料
        /// </summary>
        public string FromData(string data, bool clear, Progress progress)
        {
            Store_ tmpl;

            try
            {
                tmpl = JsonConvert.DeserializeObject<Store_>(data);
            } // try
            catch
            {
                return "from data: deserialize failed";
            } // catch

            if (tmpl == null)
                return "from data: deserialize failed";

            if (clear)
                this.data = new();

            var task = progress.Reg();
            var curr = 0;
            var total = tmpl.Count;

            foreach (var itor in tmpl)
            {
                if (this.data.ContainsKey(itor.Key))
                    return "from data: key duplicate [verifyData : " + itor.Key + "]";

                this.data[itor.Key] = itor.Value;
                curr++;
                progress.Set(task, curr, total);
            } // for

            return string.Empty;
        }

        /// <summary>
        /// 清除資料
        /// </summary>
        public void Clear()
        {
            data.Clear();
        }

        /// <summary>
        /// 取得資料
        /// </summary>
        public bool TryGetValue(Key_ key, out Data_ value)
        {
            return data.TryGetValue(key, out value);
        }

        /// <summary>
        /// 檢查索引是否存在
        /// </summary>
        public bool ContainsKey(Key_ key)
        {
            return data.ContainsKey(key);
        }

        /// <summary>
        /// 取得迭代器
        /// </summary>
        public IEnumerator<KeyValuePair<Key_, Data_>> GetEnumerator()
        {
            return data.GetEnumerator();
        }

        /// <summary>
        /// 取得資料
        /// </summary>
        public Data_ this[Key_ key]
        {
            get { return data[key]; }
        }

        /// <summary>
        /// 取得索引列表
        /// </summary>
        public ICollection<Key_> Keys
        {
            get { return data.Keys; }
        }

        /// <summary>
        /// 取得資料列表
        /// </summary>
        public ICollection<Data_> Values
        {
            get { return data.Values; }
        }

        /// <summary>
        /// 取得資料數量
        /// </summary>
        public int Count
        {
            get { return data.Count; }
        }

        private Store_ data = new Store_();
    }
}
